export const ITEM_SELECTED = "ITEM_SELECTED";
export const SELECT_ITEM_FROM_DATA_BASE = "SELECT_ITEM_FROM_DATA_BASE";
export const SELECT_ITEM_FROM_DATA_BASE_SUCCESS = "SELECT_ITEM_FROM_DATA_BASE_SUCCESS";
export const UPDATE_LIST_ITEM = "UPDATE_LIST_ITEM";
export const UPDATE_LIST_ITEM_SUCCESS = "UPDATE_LIST_ITEM_SUCCESS";
export const CLEARE_UPDATE_ITEM = "CLEARE_UPDATE_ITEM";
export const TOGGLE_CATALOG = "TOGGLE_CATALOG";

