export const FETCH_CATALOG = 'FETCH_CATALOG';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const SYNC_CATALOG = 'SYNC_CATALOG';
export const SYNC_CATALOG_STOP = 'SYNC_CATALOG_STOP';